-- 問卷調查
CREATE TABLE IF NOT EXISTS SURVEY (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '問卷調查流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    DIFFICULT INT NOT NULL COMMENT '困難程度',
    SCARY INT NOT NULL COMMENT '可怕程度',
	RECOMMENDED INT NOT NULL COMMENT '推薦程度',
	GAME_ORDER_ID NOT NULL COMMENT '訂單流水號',
    PRIMARY KEY (ID)
);

-- 會員
CREATE TABLE IF NOT EXISTS MEMBER (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '會員流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    NAME VARCHAR(12) NOT NULL COMMENT '會員姓名',
    EMAIL VARCHAR(30) NOT NULL COMMENT '電子郵件',
	PHONE VARCHAR(15) NOT NULL COMMENT '電話',
	BIRTHDAY DATE NULL COMMENT '生日',
	PASSWORD VARCHAR(45) NOT NULL COMMENT '密碼',
	REGISTER_DATE DATE NOT NULL COMMENT '註冊日期',
	BANNED TINYINT NOT NULL DEFAULT 0 COMMENT '禁用狀態, 0: 未禁用, 1: 已禁用',
    PRIMARY KEY (ID)
);

-- 優惠券
CREATE TABLE IF NOT EXISTS COUPON (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '優惠券流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    DISCOUNT INT NOT NULL COMMENT '折扣',
    MEMBER_ID INT NOT NULL COMMENT '會員流水號',
	STATUS INT NOT NULL DEFAULT 0 COMMENT '狀態, 0: 未使用, 1: 已使用',
    PRIMARY KEY (ID)
);

-- 遊戲訂單
CREATE TABLE IF NOT EXISTS GAME_ORDER (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '遊戲訂單流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    MEMBER_ID INT NOT NULL COMMENT '會員流水號',
	STORE_ID INT NOT NULL COMMENT '商店流水號',
	GAME_ID INT NOT NULL COMMENT '遊戲流水號',
	ATTENDANCE INT NOT NULL DEFAULT 0 COMMENT '參與狀況, 0: 未參與, 1: 有參與',
	ORDER_DATETIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下單時間',
	PAYMENT_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '支付狀態, 0: 未支付, 1: 已支付',
	ORDER_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '訂單狀態, 0: ?',
	TOTAL INT NOT NULL DEFAULT 0 COMMENT '總金額',
	COUPON_ID INT NULL COMMENT '優惠券流水號',
    PRIMARY KEY (ID)
);


-- 商店
CREATE TABLE IF NOT EXISTS STORE (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '商店流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    NAME VARCHAR(30) NOT NULL COMMENT '商店名(存中文，SIZE要給大一點)',
    PHONE VARCHAR(15) NOT NULL COMMENT '會員流水號',
	COUNTY VARCHAR(3) NOT NULL COMMENT '縣?還是說城市會好點?',
	DISTRICT VARCHAR(3) NOT NULL COMMENT '區',
	ROAD VARCHAR(20) NOT NULL COMMENT '道路',
	ROAD_NO VARCHAR(10) NOT NULL COMMENT '門牌號，會有之一的情況，不建議用INT',
	FLOOR TINYINT NOT NULL DEFAULT 1 COMMENT '樓層',
    PRIMARY KEY (ID)
);

-- 遊戲
CREATE TABLE IF NOT EXISTS GAME (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '遊戲流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
    NAME VARCHAR(45) NOT NULL COMMENT '遊戲名',
	STORE_ID INT NOT NULL COMMENT '商店流水號',
	ADULT_ONLY TINYINT NOT NULL DEFAULT 0 COMMENT '是否為限制級, 0: 否, 1: 是',
    PRIMARY KEY (ID)
);

-- 最新消息
CREATE TABLE IF NOT EXISTS NEWS (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '最新消息流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
	PUBLISHER_ID INT NOT NULL COMMENT '發布人',
	TOPIC VARCHAR(100) NOT NULL DEFAULT '' COMMENT '主題',
	CONTENTS VARCHAR(500) NOT NULL DEFAULT '' COMMENT '內容',
	PICTURE_ID INT NULL COMMENT '照片流水號',
	STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '狀態, 0: 未發布, 1: 已發布',
    PRIMARY KEY (ID)
);

-- 員工
CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT COMMENT '員工流水號',
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建日期',
	UPDATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日期',
	NAME VARCHAR(12) NOT NULL COMMENT '名字',
	ACCOUNT VARCHAR(45) NOT NULL COMMENT '帳號',
	PASSWORD VARCHAR(45) NOT NULL COMMENT '密碼',
    PRIMARY KEY (ID)
);


